version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    networks:
      - app-network

  streamlit:
    build: ./app
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network: